spring:
  application:
    name: data-source-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  config:
    import: optional:configserver:http://localhost:8888


management:
  endpoints:
    web:
      exposure:
        include: env,health

jasypt:
  encryptor:
    password: ${INSIGHTHUB_ENCRYPTION_KEY}

