spring:
  application:
    name: data-source-service

  data:
    mongodb:
      uri: mongodb+srv://mongo:mongo@cluster0.3upg3as.mongodb.net/?appName=Cluster0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
