spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments,/api/v1/payments/**
              filters:
                - name: inMemoryRateLimit
                  args:
                    capacity: 10
                    period: 2s
                - name: addCurrentUserHeader
                  args:
                    name: X-User-Id
      discovery:
        locator:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${supabase.project-id}.supabase.co/auth/v1
server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        cloud:
          gateway: TRACE
supabase:
  project-id: dyzdsyhinkwyauxhydhf
